[#10] 고객사 서버 - 대기열 서버 간의 인증
f-lab-edu/inqueue pull request #12
Opened 2023-04-07 12:53 UTC by JKjiwon

[#10]
## 1. Hmac 인증 - HmacSignatureVerifier
- clientSecret을 서버에 직접적으로 전달하지 않기 위해서, clientSecret으로 메세지를 암호화 Hmac 인증 방식 채택
- 현재는 암호화할 message로 http RequestUrl을 사용

## 2. 스프링 시큐리티를 이용한 인증
- 최대한 스프링 시큐리티의 구조를 지키려고 했습니다.
- HmacSignatureFilter
    - Authorization 값으로 들어온 clientId:hmacSignature 값이 올바른 형식인지만 판단
    - 실제 인증에 필요한 Authentication을 상속받아 HmacAuthenticationToken 생성
 - HmacAuthenticationProvider
    - DB로 부터 clientId 에 맞는 clientSecret 을 조회
    - 실제 검증은 HmacSignatureVerifier를 하도록 역할 분리
- ProviderManager에 HmacAuthenticationProvider 를 등록

## 3. ClientId, ClientSecret을 Factory Util 생성 - CustomerAccountFactory
- ClientId, ClientSecret은 SecureRandom()를 이용하여 난수를 생성하여 안정성 확보
- Util 클래스로 만들어 코드를 모듈화

## 4. 고객 도메인 생성
- role 을 두어 USER와 ADMIN 사이의 권한 분리

## 5. 테스트
- 통합테스트를 진행하면 전체 필터에 대한 검증이 가능하기에 통합테스트 채택
- Component Sacn 대상을 시큐리티 코드가 있는 "com.flab.inqueue.security.hmacsinature"로 제한

## 6. 추후 고려 사항
- 스프링 시큐리티에서 인증이 실패하면 기본적으로 403 에러가 발생하는 인증 실패는 401, Role에 대한 권한 실패는 403으로 변경 필요
- JWT 토큰에 대한 인증도 추가할 필요가 있는데, 추가적인 FilterChain 을 고려
- clientSecret은 실제 Hamc 해싱에도 사용해야하므로 DB 저장시 양방향 암호화 고려

@f-lab-scott , @elyo9381 6번 고려사항이 타당한지도 검토 부탁드립니다.

2023-04-08 07:24 UTC, wheejuni requested changes
한 가지만 체크해주세요!

2023-04-08 07:24 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/domain/customer/entity/Customer.kt
> +    val roles: List<Role>
관계 매핑인가요? `AttributeConverter` 사용하실 건가요?

2023-04-08 07:24 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/domain/customer/utils/CustomerAccountFactory.kt
> +object CustomerAccountFactory {
좋습니다. 👍 그런데 기왕에 싱글턴으로 관리하실 거면 Spring Bean으로 사용하시는게 낫지 않으려나요?

- `SecureRandom` 을 로직 안에서 만들어 쓰고 있는데 이것에 대해서도 의존성 역전이 일어날 수 있도록 설계해 보시면 좋습니다.
- id length, secret length를 properties(`application.yml`) 로 관리할 수 있도록 개선해 봅시다.

2023-04-08 07:24 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/security/hmacsinature/HmacAuthenticationProvider.kt
> +    }
Java <-> Kotlin 간 클래스 오브젝트의 작동이 상이한 경우가 있어서 이 부분에 대해서는 유닛 테스트도 해보시면 좋습니다.

2023-04-08 07:24 UTC, wheejuni commented
6번 의견

- 추가적인 `filterChain` 보단 그냥 `filter` 하나로 두면 되지 않을까요?
- DB 암호화 이견 없습니다.

2023-04-08 10:30 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/customer/entity/Customer.kt
> +    val roles: List<Role>
관계 맵핑으로 설정할까 합니다. @ElementCollection 으로 정의하면 어떨까 합니다.

2023-04-08 10:33 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/customer/utils/CustomerAccountFactory.kt
> +object CustomerAccountFactory {
Spring Bean으로 개선하였습니다. 또한 CustomerAccountFactoryConfig 클래스를 통해서 SecureRandom, id length, secret length 를 외부에서 주입하는것으로 변경하였습니다.

2023-04-10 07:03 UTC, JKjiwon commented
@wheejuni 
Filter Chain 을 고려했던 근거에 대해서 조금더 설명 드리겠습니다.

요청하는 url 별로 다른 인증 방식을 고려하고 있습니다.

1. /client/** 
- 대기열 사용자 - 대기열 서버 간의 인증
-  JwtToken을 사용하여 인증
- JwtAuthenticationFilter로 검증

2. /server/**
- 고객사 서버 - 대기열 서버 간의 인증
- clientId, clientSecret을 통한 hmac 인증
- HamcSignatureFilter로 검증

두 인증에 대한 진입점이 달라서, 필터 체인 또한 2개가 나오고 각각의 필터 체인에 각 필터가 등록되어야 한다고 생각했습니다.
그리고 필터 체인 내에서는 url별로 인증 방식을 선택 할 수 없어, 결국 필터 내부에서 요청 url을 필터링 해야하는데, 좋은 방법 같지 않아 보입니다.

2023-04-13 10:18 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/customer/entity/Role.kt
> +}
Customer 객체가 실제 우리 서버의 "회원" 이나 다름이 없는데, 해당 Customer에 Role 을 두어 
USER 는 실제 고객사에 대한 객체이고
ADMIN 은 우리 서버의 고객사 생성과 같은 관리자 기능을 담당하는 객체로 만들고 싶었습니다.

그래서 Customer 라는 이름은 적절하지 않은것 같아 변경이 필요할것 같습니다.

2023-04-14 09:48 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/security/hmacsinature/HmacAuthenticationProvider.kt
> +    }
유닛 테스트를 해보았는데, 해당 작동에는 문제가 없었습니다.

2023-04-20 01:49 UTC, closed without merging