대기열 진입 기능
f-lab-edu/inqueue pull request #17
Opened 2023-04-19 11:33 UTC by elyo9381

#7 

### 고려사항

1. 작업열 큐를 먼저 접근 후 , 더이상 접근하지 못하면 대기열 진입 고려
레디스에 eventId로가 대기열의 key로
eventId_JOB_QUEUE 를 작업열의 key 로 설정해서 들어가도록 구현

2. redisTemplate 를 한번 추상화

2023-04-19 11:39 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/repository/QueueRedisPository.kt
> +        jobRedisTemplate.opsForZSet().add(job.eventId, job, System.nanoTime().toDouble())
한번 추상화를 했는데 
확장 가능성? 이 없을것 같아서 클래스로 만들었습니다.

2023-04-19 11:39 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/JobService.kt
> +    }
작업열을 먼저 조회 후 대기열 진입 하도록

2023-04-19 11:39 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/JobService.kt
> +        val event = eventRepository.findByEventId(eventId) ?: throw NoSuchElementException("행사를 찾을 수 없습니다. $eventId")
eventRepository에서 조회하는것이 아닌 

EventService에서 주입받고 EventService에서 조회를 해야할까요 
EventService에서는 한번 에러 처리가 되는데 

eventRepository는 또 에러 처리 해야하는 번거로움 존재...

2023-04-19 23:01 UTC, wheejuni requested changes
수고하셨습니다. 👍 
몇가지 어려운 부분도 있고 공감가지 않는 부분들이 있는데, 이 부분은 저도 잘 모르고 그렇게 한 것이니 요엘 님이 추가적인 설명 달아주시면 더 좋은 코드 함께 만들 수 있을 듯합니다.

2023-04-19 23:01 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/JobService.kt
> +        return queueResponse(waitJob)
`QueueService.register()` 가 된 시점에 자기 순서를 이미 알고있어야 하는 건 아닌가 생각해봅니다...
이후에 추가 연산이 필요하단 점이 잘 이해가지 않습니다.

2023-04-20 01:29 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/QueueService.kt
>  }
QueueRedisPository가 레디스에 접근하는 역할을 담당하게 하신것은 좋습니다.

하지만 QueueService 제가 이해하기로는 단순히 QueueRedisPository 를 접근하는 역할하고 있는것 같아, 이 QueueService의 필요성에 대해서 의문이 듭니다.

혹시 QueueService 를 사용하는 염두해두신 다른 의도가 있는지 궁금합니다.

2023-04-20 01:36 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/dto/QueueResponse.kt
>      val status: String,
Enum으로 빼셔도 좋을것 같습니다.

2023-04-20 01:36 UTC, JKjiwon reviewed
고생하셨습니다.

2023-04-20 02:46 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/JobService.kt
> +        return queueResponse(waitJob)
대기열 큐가 존재하고 , 작업열 큐가 존재하는데 
이를 하나의 서비스에서 모두 처리해야하지 않나 ? 라는 생각이 들어서 
QueueService.register() 후에 처리가 되어야 한다고 생각 했는데요.

앞서 말씀하신  `컴포넌트의 책임` 부분을 고려 해보겠습니다.

2023-04-20 03:16 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/QueueService.kt
>  }
@JKjiwon 
그렇네요 
접근하는 역할만 하고 있었네요..! 

QueueService가 할일을 JobService에서 일부 하고 있어서 
오히려  QueueService가 의도가 부족해 진것 같습니다.

앞서 멘토님이 말씀하신  `컴포넌트의 책임` 부분을 고려 해보겠습니다

2023-04-20 07:25 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/entity/JobStatus.kt
> +    abstract val prefix : String
대기열 , 작업열에 따른 등록 및 조회가 필요하고 

redis에 insert할  prefix가 필요하다고 판단되어 
상태 Enum을 정의하였고요 prefix라는 변수를 설정하였습니다.

2023-04-20 07:25 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/entity/Job.kt
> +        this.eventId = stringBuffer.toString()
prefix를 붙여서 redis에 insert되어야 하므로
Job  객체 생성시  , 초기화를 진행 하였습니다.

2023-04-20 07:25 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/domain/queue/service/QueueServiceTest.kt
> +        }
QueueService 테스트 작성 

질문 상태에 따른 테스트가 필요하다고 생각 되어 `@ParameterizedTest`을 사용하였는데요 
상태에 따라 리턴값이 다른데 
위처럼 조건문을 설정하여서 테스트를 검증하는게 맞는것인지 ... 궁금하네요

2023-04-20 07:29 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/QueueService.kt
> +        return retrieve(job)
QueueService의 책임에 있어야 할것 같아서 
QueueService.register()에 현재 큐의 결과를 QueueResponse반환 하도록 진행하였습니다.

2023-04-20 11:14 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/JobService.kt
> +        }
대기열이 비어있는지에 대한 검증도 필요하지 않을까요?

예를 들어, 대기열에 유저가 기다리고 있는 상황이고, 작업열에서 다른 유저가 작업을 마치고 빠져나간 상황이라면...
방금 막 들어온 유저가 대기열을 거치지 않고 작업열에 바로 들어갈 수있는 상황이 생길것 같습니다.

2023-04-20 13:09 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/domain/queue/service/QueueServiceTest.kt
> +        }
코드 내 분기문이 있으니, 코드의 가독성이 조금 떨어지는 것 같습니다.

`@ParameterizedTest` 의 경우 다른 input값에 대한 동일한 결과 값이 나올 때 유용하게 쓸수 있을것 같습니다.

2023-04-20 13:24 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/queue/entity/Job.kt
> +        this.eventId = stringBuffer.toString()
eventId 에 prefix를 붙이니, eventId라는 의미가 사라지는것 같습니다. 

job.redisKey() 라는 함수로 키값을 알아내는 방식은 어떨까요?

2023-04-21 09:54 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/entity/JobStatus.kt
> +            return StringBuilder(prefix).append(":").append(eventId).toString()
@f-lab-scott @JKjiwon 
레디스의 키값이 JobStatus에 따라 달라진다고 생각하여서 
makeRedisKey() 로 뺐는데, 이 책임이 맞을까요 .. 
만들어 놓고도 확신이 안서네요

2023-05-01 13:48 UTC, wheejuni approved these changes

2023-05-01 14:20 UTC, merged