작업열 QUEUE 의 자료구조 변경
f-lab-edu/inqueue pull request #23
Opened 2023-04-21 10:19 UTC by JKjiwon

이슈번호 : [#21]

기존에는 Sorted Set 으로 작업열 queue 를 만들었으나, 작업열의 특성상 순서가 필요없으므로 Set으로 변경

2023-04-24 03:50 UTC, elyo9381 commented
### 요구사항
- 작업열의 자료구조 변경 
- redis의 set으로 변경

### 고려사항
**작업열 및 대기열 TTL 검증시 userId별로 진행**
> key = prefix:eventId:userId
value = prefix:eventId:userId
Ex) sadd “prefix:eventId:userId”  “prefix:eventId:userId”


**Set 자료구조를 통한 key size 체크**

> prefix:eventId를 키로 
prefix:eventId:userId 를 배열로 set 자료구조
Ex) sadd “prefix:eventId”  “prefix:eventId:userId”


userId 별 TTL을  적용해야한다고 생각 했습니다. 
작업열 및 대기열 전체 사이즈 (key)의 사이즈를 가져와야하는데 

set 자료구조의 키가 이렇게 된다면 EventId별 사이즈 조회에 있어서 어려움이 존재한다고 판단하였습니다.
prefix:eventId:userId
sscan 란 명령어가 존재하고 이를 통해서 진행가능하지만, 데이터가 많아질수록 느려진다는 단점이 존재합니다.

그래서 새로운 배열을 둬어 사이즈 체크를 진행하였습니다.
scard (set의 전체 사이즈 명령어) -> O(1)


![image](https://user-images.githubusercontent.com/44278562/233895975-c733c61c-3b87-4237-bde0-3cc0287cf3e5.png)

2023-04-24 04:02 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/infra/config/RedisConfig.kt
> +    }
리스너를 통해서 Expire 만료처리가 가능할것으로 보이는데요
해당 코드가 동작함을 우선 확인하였고, 어떻게 사용할지는 좀 더 고려해봐야 할것 같습니다

2023-04-24 04:02 UTC, elyo9381 commented
@JKjiwon  @f-lab-scott  확인 부탁드리겠습니다.!

2023-04-24 12:00 UTC, wheejuni requested changes
우선 간단한 의견 드리고요, 자세한 건 잠시 후 멘토링 시간에 같이 보시죠..

2023-04-24 12:00 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/domain/queue/repository/JobQueueRedisRepository.kt
> +        if(isRedisValue == true) {
굳이 `true` 와 등호 연산 하실 필요 없습니다.

```suggestion
        if(isRedisValue) {

2023-04-24 12:00 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/domain/queue/repository/JobQueueRedisRepository.kt
> +        } else {
32번줄에서 리턴했기 때문에, 엘스 문을 사용하시지 않아도 됩니다.

2023-04-24 12:00 UTC, wheejuni commented on src/main/kotlin/com/flab/inqueue/domain/queue/repository/JobQueueRedisRepository.kt
> +        redisTemplate.expire(job.redisValue(), 1L, TimeUnit.SECONDS)
네 좋습니다.

2023-04-25 13:53 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/QueueService.kt
>      }
WaitQueueRetrieve 에서 JobQueue의 isMember를 검색하는게 맞나요? 한번 확인 부탁드립니다.

2023-04-26 02:40 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/queue/service/QueueService.kt
>      }
@JKjiwon 
isMember 메소드가 
대기열, 작업열의 set 자료구조에서 userid가 존재하는지 확인하는 기능인데요
ttl이 살아 있는지확인이요 

그래서 QueueService서비스 즉 대기열 조회할때  TTL이 살아있는지 먼저 확인해야하므로, 
isMember()를 만들어놨습니다.

명칭이 `jobQueueRedisRepository` 으로 되어있지만 대기열, 작업열의 관련 set이라는 명칭이 되어야할것같고요.

2023-05-01 13:47 UTC, wheejuni approved these changes

2023-05-01 14:20 UTC, merged