[#2] 프로젝트 셋팅
f-lab-edu/inqueue pull request #3
Opened 2023-03-17 02:13 UTC by JKjiwon

2023-03-17 22:23 UTC, f-lab-scott requested changes
한번만 검토 부탁드립니다!

2023-03-17 22:23 UTC, f-lab-scott commented on build.gradle.kts
> +group = "com.flab"
`flab` 까지 하는 것보단 우리 프로젝트명까지 기입하는 것이 더 좋을 것 같기는 합니다..

```suggestion
group = "com.flab.inqueue"

2023-03-17 22:23 UTC, f-lab-scott commented on src/main/resources/application.yml
> +    password: ${PASSWORD}
요 두 항목은 그럼 어떻게 리졸브되는 걸까요?

2023-03-17 22:23 UTC, f-lab-scott commented on src/main/resources/application.yml
> +      ddl-auto: none
실 서비스 배포가 나갔을 때 ddl-auto 끄는 것에는 저도 동의하지만, 로컬에서는 개발 속도가 너무 저하될 수 있습니다.

2023-03-19 08:58 UTC, JKjiwon commented on build.gradle.kts
> +group = "com.flab"
다시 생각해보니 com.flab.inqueue 로 수정하는 것이 좋을것 같습니다.

2023-03-19 08:58 UTC, JKjiwon commented on src/main/resources/application.yml
> +    password: ${PASSWORD}
jar 파일 실행시 arguments를 통하여 전달하면 좋지 않을까 생각했습니다.
java -jar -DUSER=jiwon -DPASSWORD =jiwon ./build/libs/inqueue-0.0.1-SNAPSHOT-plain.jar

그리고 좀 더 생각해보니 properties를 분리하여, local의 db는 h2 in-memory db로 개발하는 것이 어떨까 생각합니다.

2023-03-19 09:02 UTC, JKjiwon commented on src/main/resources/application.yml
> +      ddl-auto: none
properties를 분리하여 local은 create-drop(create), dev는 none으로 설정하는 것도 괜찮을것 같습니다.

2023-03-19 14:01 UTC, f-lab-scott commented on src/main/resources/application.yml
> +    password: ${PASSWORD}
네 로컬 H2 사용 좋습니다. 좋은 판단입니다.
그리고 USER랑 PASSWORD는 환경변수로 넘어가면 좋을 것 같습니다. 환경 변수로 넘어가는데 아래와 같이 넘어가면 될 것 같습니다.

```bash
SPRING_DATASOURCE_USERNAME=
SPRING_DATASOURCE_PASSWORD=
```

즉 코드 상 컨픽 파일에는 로컬 환경에 대한 구성만 있으면 됩니다. 프로덕션 환경에서는 환경 변수로 모든 것을 통제할 수 있기 때문에요.

2023-03-19 14:01 UTC, f-lab-scott commented on src/main/resources/application.yml
> +      ddl-auto: none
네 좋습니다.

2023-03-19 14:01 UTC, f-lab-scott commented
@JKjiwon 댓글만 주시고 실제 파일에 변경사항들이 반영이 안 된 것 같습니다.

2023-03-19 15:29 UTC, JKjiwon commented on src/main/resources/application.yml
> -      maximum-pool-size: 30
해당 부분은 제거 하였습니다. 추후 성능 테스트시 다시 고려해보겠습니다.

2023-03-19 15:47 UTC, JKjiwon commented on src/main/resources/application.yml
> -        default_batch_fetch_size: 100
default_batch_fetch_size 부분은 제거 했습니다. 추후 필요시 설정하겠습니다.

2023-03-19 15:47 UTC, JKjiwon commented on src/main/resources/application.yml
> -      maximum-pool-size: 30
maximum-pool-size 부분 제거하겠습니다. 추후 필요시 설정하겠습니다.

2023-03-19 15:47 UTC, JKjiwon commented on src/main/resources/application-prod.yml
> +    open-in-view: false
prod에 대한 config yml을 생성했습니다. 멘토님께서 의도하신 방향이 맞는지 궁금합니다.

2023-03-20 03:16 UTC, f-lab-scott commented on src/main/resources/application-prod.yml
> +    open-in-view: false
@JKjiwon 네 잘하셨습니다.
다만 한 파일 내에서도 이와 같은 분리가 가능하다는 점은 알아두시면 좋습니다.
`---` 로 구분선을 넣으시고 진행하시면 됩니다!

2023-03-20 03:16 UTC, merged