[#4] api ATDD 생성
f-lab-edu/inqueue pull request #5
Opened 2023-03-28 08:10 UTC by elyo9381

멘토님 ! 

#4 
atdd 작성을 해봤는데요.

- 토큰 발급 api
- 사용자 대기열 진입 api
- 사용자 대기열 조회 api
- 사용자 작업열 검증 기능 api
- 사용자 작업열 종료 api
- 행사 도메인 CRUD

위의 api에 대해서 
- [ ] url  
- [ ] HttpMethod 
- [ ] request 또는 response

간단하게 작성해 보았습니다. 

확인 한번 부탁드리겠습니다. 

## 질문 ! 
1. response를 표현할때 간단하게 만들었는데요     
실질적인 response 객체 를 만들어서 정확하게 표현하는게 나을까요 ? 

----

### 3.30 추가 반영
- 테스트 환경 분리, Testcontainers를 통한 Mysql 추가
- Rest-Docs를 통한 문서화, objectMapper 가 아닌 Rest-assured 의 자체 검증(WebClient의 JsonPath 검증과 유사)

2023-03-28 12:05 UTC, f-lab-scott requested changes
DTO를 먼저 설계하고 나서 테스트 코드 작업하시는 것이 좋겠습니다!

2023-03-28 12:05 UTC, f-lab-scott commented on src/test/kotlin/com/flab/inqueue/api/ClientTest.kt
> +            .body(body)
`.body()` 도 이렇게 맵 형태로 넘기기 보다는요, 아래 메소드를 사용하실 수 있어요.

```kotlin
.body(Mono.just(), Class<T>::class)
```

즉 컨트롤러에서 실제 매핑될 DTO 클래스를 먼저 작성하시고, 이 테스트 케이스에서 사용해주세요.

2023-03-28 12:05 UTC, f-lab-scott commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +
불필요한 공백은 늘 제거 부탁드립니다.

2023-03-28 12:05 UTC, f-lab-scott commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +            .header("Authorization","ClientId:(StringToSign를 ClientSecret으로 Hmac 암호화)")
아직 작동하지 않는 코드인 것이죠?

2023-03-29 06:16 UTC, JKjiwon reviewed
요엘님 리뷰 남겼습니다. 확인바랍니다.!!

2023-03-29 06:16 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .statusCode(HttpStatus.OK.value())
assertThat()이 body에 대한 검증기능인데, body가 따로 없으니 빼셔도 좋을것 같습니다.

2023-03-29 06:16 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/dto/QueueResponse.kt
> +
마찬가지로 남은 시간에 대한 표시로 LocalDateTime은 적절하지 않은것 같습니다.

2023-03-29 06:16 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/ClientTest.kt
> +            .then().log().all()
event 보다 events 좋을것 같습니다.

2023-03-29 06:16 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .post("v1/jobs/{eventId}/validate")
jobs뒤에 eventId가 나오는게 약간 어색해 보입니다.
 /v1/events/{eventId}/queue-validate 이런식으로 event를 명확히 표시해두는건 어떨까요?

2023-03-29 06:16 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .post("v1/jobs/{eventId}/finish")
이것도 위와 마찬가지 입니다.

2023-03-29 06:25 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/UserTest.kt
> +    private val objectMapper = ObjectMapper()
이것도 나중을 고려해서 @Autowired로 주입받아서 사용하는게 좋을것 같습니다.

@Autowired
private lateinit var objectMapper: ObjectMapper

2023-03-29 06:29 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/dto/AuthRequest.kt
> +)
이건 제가 자주 쓰는 코딩 스타일인데요... 습관처럼 작성했네요 
dto를 저렇게 한군데에 몰아서 작성하면 관리하기 편해서 ? 그렇게 해놨는데요

이건 추후에 정하도록하시죠 ! 
1. 패키지를 만들어서 관련된  객체별(dto) 클래스파일을  생성해서 관리한다. 
2. 저런식으로 한군데에 몰아 넣고 관리한다.

2023-03-29 06:29 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/dto/AuthRequest.kt
> +)
토큰발급 api가 고객사 서버에서 대기열 서버로 인증하고 userId를 생성하는 것 이기 때문에 userId를 뺐습니다.

2023-03-29 06:43 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .contentType(MediaType.APPLICATION_JSON_VALUE)
userId 를 넘겨 받아야 할것 같습니다.
아래 작업열 종료도 마찬가지입니다.

2023-03-29 06:47 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .post("v1/jobs/{eventId}/validate")
그렇네요 
/v1/events/{eventId}/~~ 로 시작해야 뭔가 통일성이 있는것 같습니다. 
그러면 
이 api가 작업큐에 존재하는지 체크하는건데 queue-validate 이걸로는 api가 무슨 api인지 감이 잘 안오는데 
job-queue-check 
이건 어떠세요 ?

2023-03-29 06:52 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/dto/EventRequest.kt
> +    val time: LocalDateTime,
그러면 수정해 놓을게요 , 혹시 다른거 더 뺄거 있을거같으세요 ? 
장소, 설명도 사실 중요하지는 않는것 같기도 해서요

2023-03-29 06:53 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/dto/QueueResponse.kt
> +
음... 그러면 저희 이걸 먼저 정해야할까요 
"time" : ISO-8601(hh:mm:ss+09:00), // 남은 시간(기준 시간 명시)

대기시간을 이렇게 보여줄건데 
커스텀 하게 만들어서 대기시간을 보여줘야할까요 ?

대기시간이 길어져서 하루가 지나면 어떻게 보여줘야할까요
예를들어 23:59:59 보다 시간이 더 대기시간이 길어지면 
- dd hh:mm:ss 
- 24시간이 넘어가면 25시간,점차적으로 크게 보여줄지 정해야할것 같습니다.

2023-03-29 06:54 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .post("v1/jobs/{eventId}/validate")
네 좋습니다.

2023-03-29 06:55 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/dto/EventRequest.kt
> +    val redirectUrl: String
그렇네요 수정할게요 ~

2023-03-29 07:01 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/dto/QueueResponse.kt
> +
위와 마찬가지로 남은 시간을 Second로 보내면 클라이언트 측에서 적절하게 파싱을 하도록 하는게 어떨까요?

2023-03-29 07:05 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/dto/AuthRequest.kt
> +)
제 생각에는 추후 고객사 서버쪽에서 호출하는 "작업열 종료, 작업열 검증"에서 유저 식별자를 전달 받아야 할텐데...
그렇게 생각하면 우리 서버가 해당 유저를 식별 할때, 고객사 서버도 알고 있는 값으로 식별하는게 좋아 보입니다.

2023-03-29 07:10 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/dto/QueueResponse.kt
> +
그러면 우선 스팩이 api 스팩이 달리지는데 
api 사용자가 불편할것 같기도 하고요 , 클라이언트쪽에서 한번 계산을 해야 하니깐요.
이거에 대해서는 다시 한번 알아보시는걸로 하는거 어떠십니까 ?

2023-03-29 07:14 UTC, JKjiwon commented on src/test/kotlin/com/flab/inqueue/dto/EventRequest.kt
> +    val time: LocalDateTime,
time이 startTime, endTime과 겹치는것 같아서 말씀드렸습니다. 
뭘 더 뺄지는 조금 더 생각해봅시다..

2023-03-29 07:27 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/UserTest.kt
> +    private val objectMapper = ObjectMapper()
좋은 의견이네요 ! 👍

2023-03-29 07:27 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .contentType(MediaType.APPLICATION_JSON_VALUE)
지원님 한번 확인 부탁드려요 ~

2023-03-29 07:29 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/ClientTest.kt
> +            .body(body)
.body(Mono.just(), Class<T>::class)를 사용하지는 않고 

body에 DTO 인스턴스 변수를 넣도록 수정하였습니다. 

.body(Mono.just(), Class<T>::class)이건 그냥 예시인거죠 ? 
저희는 모노를 안쓰니 혹시 이걸쓰시란 말씀인지 헷갈려서요

2023-03-29 07:30 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +            .header("Authorization","ClientId:(StringToSign를 ClientSecret으로 Hmac 암호화)")
네 아직 동작 하지 않습니다. 
테스트가 모두 동작하지 않는것부터 작성해서 동작 가능하게 바꾸는걸로 ATDD를 이해하였습니다.

2023-03-29 08:14 UTC, JKjiwon reviewed
한번더 확인 부탁드립니다.!

2023-03-29 08:28 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .post("v1/jobs/{eventId}/finish")
@JKjiwon 요거 해결되었으면 닫아도 될까요?

2023-03-29 08:42 UTC, elyo9381 commented on src/test/kotlin/com/flab/inqueue/api/QueueTest.kt
> +                .post("v1/event/{eventId}/job-queue-check")
@JKjiwon 
뭐가 더 나을까요?
userId에 대해 url에서 path variable로 받는거
혹은 requestBody로 받는거랑요 

파라미터가 String 두개 뿐인데 , 
requestBody 로 받으면 객체를 생성하는 과정이 생기니깐 불필요한거 아닌가 라는 생각이들어서요. 
v1/event/{eventId}/job-queue-check/{userId}
를 추가 해놓고 멘토님께 한번 여쭤보는걸로 하심이 어떠신가요 ?

2023-04-01 00:10 UTC, f-lab-scott requested changes
지난번 멘토링 시간때 남겼던 댓글이 같이 묻어있네요. 참고하고 봐주세요~

2023-04-01 00:10 UTC, f-lab-scott commented on src/test/kotlin/com/flab/inqueue/api/ClientTest.kt
> +            .body(body)
아 네 맞습니다

2023-04-01 00:10 UTC, f-lab-scott commented on src/test/resources/docker-compose.yml
> +version: '3'
요 파일은 필요 없기는 합니다만... .어떤 목적이실까요?

2023-04-01 00:10 UTC, f-lab-scott commented on src/test/resources/application.yml
> +    url:  jdbc:tc:mysql:8:///test-db
👍

2023-04-01 15:00 UTC, f-lab-scott approved these changes
이제 코드레벨의 이슈는 없는 듯한데 빠르게 머지하고 다음 스텝으로 넘어가면 어떨까 싶습니다. 🙇 
댓글 잘 확인하였습니다. 이견 없습니다.
참고로 빌드에서는 테스트 자체를 패스하는 것도 방법이라고 보긴 합니다.

2023-04-02 11:13 UTC, merged