이벤트 도메인 개발
f-lab-edu/inqueue pull request #9
Opened 2023-04-02 13:43 UTC by elyo9381

멘토님 리뷰 부탁 드리겠습니다. !

## 구현 목록 
- [ ] EventService
- [ ] EventDomain
- [ ] EventRepository
- [ ] 단위 테스트작성

## 고려사항 

**도메인 정리**
1. 임베디드 VO 를 사용해서 객체를 단순화 고려 하였습니다.
2. 뮤터불한 값과 임뮤터블한값을 정의 고려해서 도메인생성 하였습니다.
	1. 하지만 DB단에서 명시해야할 nullable은  @Column 으로 표시 

**조회 및 수정을 고려한 응답값 수정**
- api 행사 조회했던 값을 그대로 받아서 업데이트 하는게 편하겠다고 생각했습니다. 
- 그래서 조회시의 응답값을 수정 요청시의  requestDTO에 동일 하게 적용하였습니다.

**변경감지를 필요시에만 사용하려고 고려**
- Service딴에서 Transaction(read)를 하고 update같이 필요시에만 사용하려고 고려 작성하였습니다.

**Mapper를 안쓰려고 구현**
- 임베디드를 사용하기 때문에, 매핑의 어려움 존재할것이라 판단 하였습니다. 
- 오히려 무분별한 매퍼를 사용시 코드가 더 복잡해지지 않을까 고려 하였습니다.
- 테스트시에 reqeust객체에서 바로 생성가능해서 편리합니다.

**시퀀스로 사용할 id 필드를 @MappedSuperclass 사용해 추상클래스로 추출 고려**
- 앞으로 모든 도메인에 추가될것으로 모두 공통적으로 사용한다고 생각 하였습니다.

**eventId를 UUID로 선언 및 id 검증을 requestDTO단에 최초 검증**
- 실질적으로 api가 따로 존재하지만 request시에 eventId가 존재하면 수정, 없으면 저장으로 판단되다고 생각 하였습니다.
- 그래서 eventId 검증이 필요하다고 생각하여 EventRequestDTO단에 검증을 고려 하였습니다.

**반복적인 테스트 애노테이션을 줄이려고 Test에 BaseTest 애노테이션 클래스를 만들었습니다.**

----
질문
1. PR 요청드릴때, 이런걸 작성하는게 맞을까요..?

2023-04-03 14:46 UTC, f-lab-scott requested changes
수고하셨습니다. 👍

2023-04-03 14:46 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/common/domain/BaseEntity.kt
> +abstract class BaseEntity(
`public` 까먹으시면 안 됩니다..! 필요 없을 수도 있겠지만 이 상황에선 붙이는게 맞을 거 같습니다

2023-04-03 14:46 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/dto/EventRequest.kt
> +    val eventInformation: EventInformation? = null,
취향이지만 `EventInformation` 도 이 파일에 같이 있는게 좋을 것 같긴 합니다.

2023-04-03 14:46 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/dto/EventResponse.kt
> +    }
`constructor` 활용도 좋지만 `companion object` 에 정의해 보시는 건 어떨지요?

2023-04-03 14:46 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +    @Column()
아무 값도 지정하지 않을 거라면, 그냥 떼셔도 됩니다.

2023-04-03 14:46 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +    }
요거의 필요성은 좀 생각해보고 싶습니다.
왜 업데이트 해야 하나요? 그냥 버리고, 새로 저장하면 안되는 건지요?

2023-04-03 14:46 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/service/EventService.kt
> +@Transactional(readOnly = true)
아래에 이것을 뒤집는 설정을 넣으신 것 같은데, 그렇다면... 클래스 레벨에 이것이 왜 있어야 하는지 모르겠어요.

2023-04-04 11:41 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/common/domain/BaseEntity.kt
> +abstract class BaseEntity(
전역적인 사용을 고려하였으니, 접근 지시자를 public 명시를 숙지 하겟습니다.

2023-04-04 11:41 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/event/dto/EventResponse.kt
> +    }
companion object 추천하신 이유를 고려 해봤는데요.

우선 생성자로 만든이유는 event 객체를 받아서 추가적인 정보 전달의 목적으로 만들었습니다.

companion object를 추천하시는 이유가 
EventResponse를 생성자로 만들면 추가적으로 응답을 보낼때마다 생성이 되어야하고, 
companion object를 사용하면 GC의 대상이 되지는 않지만, 한번 생성해두면 객체를 계속적으로 사용하므로 조금 더 이점이 생기는 이유 때문일까요 ?

2023-04-04 11:41 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +    }
고객사에서 행사 정보를 수정할때, 명확하게 하려는 의미에서  나눠 놓았어요 
그리고 수정시 변경감지를 통해서 수정을 하려고 하였습니다.

새로 저장한다는 말씀은 행사가 한번 잘못된 정보로 생성되면, 이 행사는 다시 못쓰는 걸로 되는걸까요..  ? 
관리하는 측면에서 이상한 데이터가 계속 생길것 같아서요. 

제가 잘 이해 한것이 맞는지 궁금하네요

2023-04-04 11:41 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/event/service/EventService.kt
> +@Transactional(readOnly = true)
@Transactional(readOnly = true) 성능상의 이점이 있다고 해서 사용하였는데요.
@Transactional의 우선순위가. 메소드 ,클래스 , 인터페이스 순으로 간다고 알고있어서요 
클래스에 하나만 선언하면 모두 적용되지 않을까 해서 클래스 레벨에 적용하였습니다.

그리고  update만 변경 감지를 사용하려고 update()만 트랜잭션을 따로 설정한거였습니다. 

말씀후에 생각해보니 save()도 읽기 전용이 아닌데,  클래스단에 놓은 것 같긴하네요.

retrieve()메소드 같이 읽기 전용 함수에만 따로 적용하는것이 나을까요.?

2023-04-04 14:04 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/dto/EventResponse.kt
> +    }
1. companion object는 Java 의 static 개념으로 객체 계속 사용과 무관합니다. 싱글턴 패턴과 혼동하신 걸까요?
2. 저는 생성자는 가급적이면 값 할당에 집중하고, 로직이 단순해야 한다고 봅니다. 특히 코틀린은 named parameter도 지원하니, 생성자는 생성자대로 가만히 두고, 별도 스태틱 메소드를 통해 객체 생성을 일원화하면 어떨까 싶은 것입니다.

2023-04-05 12:37 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +    }
@elyo9381 아 이해하였습니다. 최근 update를 잘 안쓰다보니... 제가 혼동했네요.

2023-04-05 13:11 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/dto/EventResponse.kt
> +    }
```kotlin
data class EventResponse(
    val a: String? = null
    val b: String? = null
    val c: String? = null
)

val response = EventResponse(
    a = "hello",
    b = "world"
)

2023-04-09 07:47 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/event/dto/EventResponse.kt
> +    }
@f-lab-scott 
kotlin 정적 개념에 착각이 있었네요.. 

코틀린에서 생성자 사용시 네임드 파라미터 ,
복사 생성자에 대한 개념을 더 확인해보겠습니다. !

2023-04-12 02:50 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +) : BaseEntity() {
@f-lab-scott 
멘토님 엔티티 클래스 생성시에 
제가 이전에 고려했던 클래스 생성 방법 에 대한 설명과 
이해하기 쉬운 코드를 고려 하고 난후에 변경한 것에 대한 생각을 좀 적었는데요 

현재 변경된 코드가  이해하기 쉬운 코드를 생각해본 경우 입니다. 

[https://github.com/f-lab-edu/inqueue/wiki/%EA%B3%A0%EB%A0%A4](https://github.com/f-lab-edu/inqueue/wiki/%EA%B3%A0%EB%A0%A4)

2023-04-12 14:48 UTC, JKjiwon commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +) : BaseEntity() {
@elyo9381 제가 생각하는 바를 조심스럽게 남겨봅니다.

고려1, 고려2
두 방식 모두 흔히 알려진 방법 같습니다. 그래서 팀 내에서 컨밴션으로 정해야 하는 문제 같습니다.
그리고 setter를 지양하기 위해서 method()를 쓰는 방법은 좋은 방법이라고 생각합니다.
또한 고려2번에서처럼 var로 선언하되 최대한 setter를 지양하고 method()를 쓰는 방법도 있는것 같습니다.

dataclass
좋은 내용입니다.
다만 아래와 같은 만일의 실수를 줄이기 위해서 모든 변수가 생성자에 포함되도록 구현하는 것이 좋아 보입니다.

2023-04-12 14:52 UTC, f-lab-scott commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +) : BaseEntity() {
@elyo9381 저는 코틀린을 코틀린스럽게 쓰는 방식은 고려 2라고 생각해서, 고려 2 옵션을 추천하고 싶긴 합니다.
data class 사용을 고려하고 계시다면, [이 글](https://multifrontgarden.tistory.com/286) 을 읽어보시길 추천합니다.

2023-04-13 02:17 UTC, elyo9381 commented on src/main/kotlin/com/flab/inqueue/domain/event/entity/Event.kt
> +) : BaseEntity() {
@JKjiwon @f-lab-scott 
네 감사합니다. 

고려2번을 통한 컨벤션을 진행하도록 하겠습니다. 

data class는 공부하는 김에 작성해 놓았습니다. 
class 와 data class에 대해서 모르는 부분이 있는것 같아서요 !

2023-04-13 02:18 UTC, merged